name: workshop39
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Network
  dio: ^3.0.9
  data_connection_checker: ^0.3.4
  json_annotation: ^3.0.1
  cached_network_image: ^2.2.0+1
  # Storage
  flutter_secure_storage: ^3.3.3
  shared_preferences: ^0.5.8
  # Architecture
  dartz: ^0.9.1
  rxdart: ^0.24.1
  logging: ^0.11.4
  # Service locator
  get_it: ^4.0.2
  # UI
  cupertino_icons: ^0.1.3
  auto_size_text: ^2.1.0
  # Bloc for state management
  equatable: ^1.2.2
  flutter_bloc: ^5.0.1
  bloc: ^5.0.1
  flutter_form_bloc: ^0.15.1
  form_bloc: ^0.15.0
  # Navigation
  auto_route: ^0.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Build
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  # UI
  toast: ^0.1.5
  auto_route_generator: ^0.6.6
  font_awesome_flutter: ^8.8.1
  # Lint
  effective_dart: ^1.2.0

flutter:

  uses-material-design: true